# Generated by Django 5.1.3 on 2024-12-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userProfilePicture', models.ImageField(upload_to='static/profilePhoto/')),
                ('userName', models.CharField(max_length=20)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('eventTitle', models.CharField(max_length=50)),
                ('eventDescription', models.TextField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.day')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoID', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='static/memory')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.event')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.user'),
        ),
    ]
