# Generated by Django 5.1.3 on 2024-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='userProfilePicture',
            field=models.ImageField(upload_to='profilePhoto/'),
        ),
    ]
